version: "3"
services:
  webzash:
    # build: .
    image: wpayne/webzash:stable
    container_name: webzash
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "22:22"
    environment:
      CAKEPHP_WEBROOT: /var/www/webzash/app/webroot/
    links:
      - webzash_db
    # volumes:
    #   - './data/localdb/:/var/www/webzash/app/Plugin/Webzash/Database/:Z'
  webzash_db:
    image: mariadb:10
    container_name: webzash_db
    environment:
      MYSQL_DATABASE: webzash
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - './data/db:/var/lib/mysql'